theme: jekyll-theme-architect
title: "Conception Logicielle"
description: "Site web officiel du cours INF5153 de l'UQAM (Sébastien Mosser)"
github:
  owner_url: https://github.com/mosser
  owner_name: Sébastien Mosser
